server:
  port: 8081

spring:
  application:
    name: blog-portal
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    access-key-id: access_key_id
    access-key-secret: access_key_secret
    bucket-name: simple-oss-1
    dir-prefix: blog/images/

security:
  white-list:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /admin/login
    - /admin/register
    - /admin/logout