server:
  port: 8080

# datasource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_blog?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  redis:
    host: localhost
    port: 6379
    timeout: 300ms

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

# security config
secure:
  ignored:
    urls:
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /admin/login
      - /admin/register
      - /admin/logout