server:
  port: 8080

spring:
  application:
    name: blog-admin
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: access_key_id
    accessKeySecret: access_key_secret
    bucketName: simple-oss-1
    dirPrefix: blog/images/

security:
  whiteList:
    - /**/*.js
    - /**/*.css
    - /**/*.png
    - /**/*.ico
    - /admin/login
    - /admin/register
    - /admin/logout