server:
  port: 8080

spring:
  application:
    name: blog-admin
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

secure:
  ignored:
    urls:
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /admin/login
      - /admin/register
      - /admin/logout