spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_blog?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  redis:
    host: localhost
    port: 6379
    timeout: 300ms